import generateDates from '../generateDates';
import monthsData from '../monthsData';

describe('monthsData', () => {
  test('should return list of tuples with month key and list of dates', () => {
    const dates = generateDates({ startISODate: '2020-03-01', endISODate: '2020-04-30' });
    expect(monthsData(dates)).toEqual([
      [
        '2020-03',
        [
          {
            dayIndex: 0,
            day: '1',
            dayOfWeek: 0,
            dayString: '2020-03-01',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 1,
            day: '2',
            dayOfWeek: 1,
            dayString: '2020-03-02',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 2,
            day: '3',
            dayOfWeek: 2,
            dayString: '2020-03-03',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 3,
            day: '4',
            dayOfWeek: 3,
            dayString: '2020-03-04',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 4,
            day: '5',
            dayOfWeek: 4,
            dayString: '2020-03-05',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 5,
            day: '6',
            dayOfWeek: 5,
            dayString: '2020-03-06',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 6,
            day: '7',
            dayOfWeek: 6,
            dayString: '2020-03-07',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 7,
            day: '8',
            dayOfWeek: 0,
            dayString: '2020-03-08',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 8,
            day: '9',
            dayOfWeek: 1,
            dayString: '2020-03-09',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 9,
            day: '10',
            dayOfWeek: 2,
            dayString: '2020-03-10',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 10,
            day: '11',
            dayOfWeek: 3,
            dayString: '2020-03-11',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 11,
            day: '12',
            dayOfWeek: 4,
            dayString: '2020-03-12',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 12,
            day: '13',
            dayOfWeek: 5,
            dayString: '2020-03-13',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 13,
            day: '14',
            dayOfWeek: 6,
            dayString: '2020-03-14',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 14,
            day: '15',
            dayOfWeek: 0,
            dayString: '2020-03-15',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 15,
            day: '16',
            dayOfWeek: 1,
            dayString: '2020-03-16',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 16,
            day: '17',
            dayOfWeek: 2,
            dayString: '2020-03-17',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 17,
            day: '18',
            dayOfWeek: 3,
            dayString: '2020-03-18',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 18,
            day: '19',
            dayOfWeek: 4,
            dayString: '2020-03-19',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 19,
            day: '20',
            dayOfWeek: 5,
            dayString: '2020-03-20',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 20,
            day: '21',
            dayOfWeek: 6,
            dayString: '2020-03-21',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 21,
            day: '22',
            dayOfWeek: 0,
            dayString: '2020-03-22',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 22,
            day: '23',
            dayOfWeek: 1,
            dayString: '2020-03-23',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 23,
            day: '24',
            dayOfWeek: 2,
            dayString: '2020-03-24',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 24,
            day: '25',
            dayOfWeek: 3,
            dayString: '2020-03-25',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 25,
            day: '26',
            dayOfWeek: 4,
            dayString: '2020-03-26',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 26,
            day: '27',
            dayOfWeek: 5,
            dayString: '2020-03-27',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 27,
            day: '28',
            dayOfWeek: 6,
            dayString: '2020-03-28',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 28,
            day: '29',
            dayOfWeek: 0,
            dayString: '2020-03-29',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 29,
            day: '30',
            dayOfWeek: 1,
            dayString: '2020-03-30',
            month: '03',
            year: '2020',
          },
          {
            dayIndex: 30,
            day: '31',
            dayOfWeek: 2,
            dayString: '2020-03-31',
            month: '03',
            year: '2020',
          },
        ],
      ],
      [
        '2020-04',
        [
          {
            dayIndex: 31,
            day: '1',
            dayOfWeek: 3,
            dayString: '2020-04-01',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 32,
            day: '2',
            dayOfWeek: 4,
            dayString: '2020-04-02',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 33,
            day: '3',
            dayOfWeek: 5,
            dayString: '2020-04-03',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 34,
            day: '4',
            dayOfWeek: 6,
            dayString: '2020-04-04',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 35,
            day: '5',
            dayOfWeek: 0,
            dayString: '2020-04-05',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 36,
            day: '6',
            dayOfWeek: 1,
            dayString: '2020-04-06',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 37,
            day: '7',
            dayOfWeek: 2,
            dayString: '2020-04-07',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 38,
            day: '8',
            dayOfWeek: 3,
            dayString: '2020-04-08',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 39,
            day: '9',
            dayOfWeek: 4,
            dayString: '2020-04-09',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 40,
            day: '10',
            dayOfWeek: 5,
            dayString: '2020-04-10',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 41,
            day: '11',
            dayOfWeek: 6,
            dayString: '2020-04-11',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 42,
            day: '12',
            dayOfWeek: 0,
            dayString: '2020-04-12',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 43,
            day: '13',
            dayOfWeek: 1,
            dayString: '2020-04-13',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 44,
            day: '14',
            dayOfWeek: 2,
            dayString: '2020-04-14',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 45,
            day: '15',
            dayOfWeek: 3,
            dayString: '2020-04-15',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 46,
            day: '16',
            dayOfWeek: 4,
            dayString: '2020-04-16',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 47,
            day: '17',
            dayOfWeek: 5,
            dayString: '2020-04-17',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 48,
            day: '18',
            dayOfWeek: 6,
            dayString: '2020-04-18',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 49,
            day: '19',
            dayOfWeek: 0,
            dayString: '2020-04-19',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 50,
            day: '20',
            dayOfWeek: 1,
            dayString: '2020-04-20',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 51,
            day: '21',
            dayOfWeek: 2,
            dayString: '2020-04-21',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 52,
            day: '22',
            dayOfWeek: 3,
            dayString: '2020-04-22',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 53,
            day: '23',
            dayOfWeek: 4,
            dayString: '2020-04-23',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 54,
            day: '24',
            dayOfWeek: 5,
            dayString: '2020-04-24',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 55,
            day: '25',
            dayOfWeek: 6,
            dayString: '2020-04-25',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 56,
            day: '26',
            dayOfWeek: 0,
            dayString: '2020-04-26',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 57,
            day: '27',
            dayOfWeek: 1,
            dayString: '2020-04-27',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 58,
            day: '28',
            dayOfWeek: 2,
            dayString: '2020-04-28',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 59,
            day: '29',
            dayOfWeek: 3,
            dayString: '2020-04-29',
            month: '04',
            year: '2020',
          },
          {
            dayIndex: 60,
            day: '30',
            dayOfWeek: 4,
            dayString: '2020-04-30',
            month: '04',
            year: '2020',
          },
        ],
      ],
    ]);
  });
});
